### ISSUE TITLE
"Save" button in application edit does not work when no IP filter is given

### ISSUE THREAD

**Issue by cutemachine** [steemit/steemconnect#289] opened 2018-05-18 06:38 UTC
I have set up an app in Steemconnect. The app is listed in Steemconnect. So all is fine.

But when I try to edit the settings for this app on the  https://v2.steemconnect.com/apps/@APPNAME/edit, Steemconnect does not allow to save my changes. 

The save button does not work because I did not fill in the Allowed IPs section, although it should work without IP filtering.

It seems that this bug has been introduced by [PR 270](https://github.com/steemit/steemconnect/pull/270), but I am not sure.

When one is building a mobile app and there is no server what should one enter in the Allowed IPs section?

**Comment by gregory-latinier** [comment] 2018-05-18 07:58
Duplicate of #278

**Closed by gregory-latinier** 2018-05-18 07:58 UTC
