### ISSUE TITLE
https://steemconnect.com/api/oauth2/token stopped working

### ISSUE THREAD

**Issue by DSofter** [steemit/steemconnect#273] opened 2018-05-08 20:16 UTC
Hello guys, the `/api/oauth2/token` endpoint has seem to be broken. Any idea what happened?

![image](https://user-images.githubusercontent.com/1687829/39780727-1234fd08-52c2-11e8-958e-063d2b8a1a3e.png)

Thanks!

**Comment by bonustrack** [comment] 2018-05-08 20:47
Duplicate of #272

**Closed** 2018-05-10 02:55 UTC
